---
# tasks file for apache
- name: Clone a repository
  git:
    repo: https://github.com/komarserjio/notejam.git
    dest: /opt/myproject/notejam
    force: yes
  become: yes

- name: Install django
  pip:
    name:
      django==1.8

- name: make changes in db config
  lineinfile:
    path: /opt/myproject/notejam/django/notejam/notejam/settings.py
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "        'ENGINE'", line: "        'ENGINE': 'django.db.backends.postgresql_psycopg2'," }
    - { regexp: "        'NAME'", line: "        'NAME': 'myproject'," }
    - { regexp: "        'USER'", line: "        'USER': 'aaa'," }
    - { regexp: "        'PASSWORD'", line: "        'PASSWORD': 'aaa'," }
    - { regexp: "        'HOST'", line: "        'HOST': '54.183.231.199'," }
    - { regexp: "south", line: "#south" }
  become: yes

- name: Install libpq-dev
  apt:
    name: libpq-dev
    state: present
  become: yes

- name: Install postgresql-common
  apt:
    name: postgresql-common
    state: present
  become: yes

- name: Install psycopg2
  pip:
    name:
      psycopg2

- name: makemigrations
  command: python /opt/myproject/notejam/django/notejam/manage.py makemigrations

- name: migrate
  command: python /opt/myproject/notejam/django/notejam/manage.py migrate

- name: runserver
  command: python /opt/myproject/notejam/django/notejam/manage.py runserver 0.0.0.0:8000
    


