---
# tasks file for apache
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: yes
- name: Install python
  apt:
    name: python2.7
    state: present
  become: yes
- name: install pip
  apt:
    name: python-pip
    state: present
  become: yes
- name: Clone a repository
  git:
    repo: https://github.com/komarserjio/notejam.git
    dest: /opt/myproject/
    force: yes
  become: yes
- name: Install django
  pip:
    name:
      django>1.8
- name: make changes in db config
  lineinfile:
    path: /opt/myproject/django/notejam/notejam/settings.py
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "        'ENGINE'", line: "        'ENGINE': 'django.db.backends.postgresql_psycopg2'," }
    - { regexp: "        'NAME'", line: "        'NAME': 'myproject'," }
    - { regexp: "        'USER'", line: "        'USER': 'aaa'," }
    - { regexp: "        'PASSWORD'", line: "        'PASSWORD': 'aaa'," }
    - { regexp: "        'HOST'", line: "        'HOST': '54.215.92.194'," }
    - { regexp: "south", line: "#south" }

  become: yes

- name: Install libpq-dev
  apt:
    name: libpq-dev
    state: present
  become: yes

- name: Install postgresql-common
  apt:
    name: postgresql-common
    state: present
  become: yes

- name: Install psycopg2
  pip:
    name:
      psycopg2

- name: Install django-inspect
  pip:
    name:
      django-inspect
