---
# tasks file for apache
- name: Clone a repository
  git:
    repo: '{{ git_repo }}'
    dest: '{{ project_folder }}'
    force: yes
  become: yes

- name: Install django
  pip:
    name:
      django=={{ django_version }}
  
  
     

