---
# tasks file for apache
- name: Clone a repository
  git:
    repo: '{{ git_repo }}'
    dest: '{{ project_folder }}'
    force: yes
  become: yes

- name: Install django
  pip:
    name:
      django=={{ django_version }}

- name: make changes in db config
  lineinfile:
    path: {{ settings.py_path }}
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "        'ENGINE'", line: "        'ENGINE': 'django.db.backends.postgresql_psycopg2'," }
    - { regexp: "        'NAME'", line: "        'NAME': '{{ db_name }}'," }
    - { regexp: "        'USER'", line: "        'USER': '{{ db_username }}'," }
    - { regexp: "        'PASSWORD'", line: "        'PASSWORD': '{{ db_pass }}'," }
    - { regexp: "        'HOST'", line: "        'HOST': '{{ db_addr }}'," }
    - { regexp: "south", line: "#south" }
  become: yes

- name: Install libpq-dev
  apt:
    name: libpq-dev
    state: present
  become: yes

- name: Install postgresql-common
  apt:
    name: postgresql-common
    state: present
  become: yes

- name: Install psycopg2
  pip:
    name:
      psycopg2

- name: makemigrations
  command: python {{ manage.py_path }} makemigrations

- name: migrate
  command: python {{ manage.py_path }} migrate

#- name: runserver
#  command: python /opt/myproject/notejam/django/notejam/manage.py runserver 0.0.0.0:8000

#- name: Clone a repository where is notejam.service file
#  git:
#    repo: https://github.com/Django-automation/files.git
#    dest: /home/ubuntu/files
#    force: yes
  
- name: Copy notejam.service
  copy:
    src: /home/ubuntu/completing-task/roles/notejam/files/notejam.service
    dest: /etc/systemd/system/notejam.service
  become: yes

- name: daemon-reload
  command: systemctl daemon-reload
  become: yes
 
- name: make manage.py executable
  command: chmod +x {{ manage.py_path }}
  become: yes   
  
- name: start notejam.service
  command: systemctl start notejam.service
  become: yes
  
- name: enable notejam.service
  command: systemctl enable notejam.service
  become: yes  
  
  
     

