---
# tasks file for apache
- name: Clone a repository
  git:
    repo: https://github.com/komarserjio/notejam.git
    dest: /opt/myproject/notejam
    force: yes
  become: yes

- name: Install django
  pip:
    name:
      django==1.8

- name: make changes in db config
  lineinfile:
    path: /opt/myproject/notejam/django/notejam/notejam/settings.py
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "        'ENGINE'", line: "        'ENGINE': 'django.db.backends.postgresql_psycopg2'," }
    - { regexp: "        'NAME'", line: "        'NAME': 'myproject'," }
    - { regexp: "        'USER'", line: "        'USER': 'aaa'," }
    - { regexp: "        'PASSWORD'", line: "        'PASSWORD': 'aaa'," }
    - { regexp: "        'HOST'", line: "        'HOST': '52.53.194.15'," }
    - { regexp: "south", line: "#south" }
  become: yes

- name: Install libpq-dev
  apt:
    name: libpq-dev
    state: present
  become: yes

- name: Install postgresql-common
  apt:
    name: postgresql-common
    state: present
  become: yes

- name: Install psycopg2
  pip:
    name:
      psycopg2

- name: makemigrations
  command: python /opt/myproject/notejam/django/notejam/manage.py makemigrations

- name: migrate
  command: python /opt/myproject/notejam/django/notejam/manage.py migrate

#- name: runserver
#  command: python /opt/myproject/notejam/django/notejam/manage.py runserver 0.0.0.0:8000

#- name: Clone a repository where is notejam.service file
#  git:
#    repo: https://github.com/Django-automation/files.git
#    dest: /home/ubuntu/files
#    force: yes
  
- name: Copy notejam.service
  copy:
    src: /home/ubuntu/.ansible/roles/notejam/files/notejam.service
    dest: /etc/systemd/system/notejam.service
  become: yes

- name: daemon-reload
  command: systemctl daemon-reload
  become: yes
 
- name: make manage.py executable
  command: chmod +x /opt/myproject/notejam/django/notejam/manage.py
  become: yes   
  
- name: start notejam.service
  command: systemctl start notejam.service
  become: yes
  
- name: enable notejam.service
  command: systemctl enable notejam.service
  become: yes  
  
  
     

