- name: Copy notejam.service
  copy:
    src: /home/ubuntu/completing-task/roles/notejam/files/notejam.service
    dest: /etc/systemd/system/notejam.service
  become: yes

- name: daemon-reload
  command: systemctl daemon-reload
  become: yes
 
- name: make manage.py executable
  command: chmod +x {{ managepy_path }}
  become: yes   
  
- name: start notejam.service
  command: systemctl start notejam.service
  become: yes
  
- name: enable notejam.service
  command: systemctl enable notejam.service
  become: yes  
